#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

title: Apache Pulsar
description: Distributed pub-sub messaging system
encoding: utf-8
permalink: pretty
pulsar_repo: https://github.com/apache/incubator-pulsar/tree/master
baseurl: /incubator-pulsar/
destination: ../generated-site/content

versions:
- 1.18
latest: 1.18

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3

defaults:
- scope:
    path: docs
  values:
    layout: docs
- scope:
    path: ja
  values:
    layout: docs-ja

exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- package.json
- popovers.yaml
- Makefile
- scripts
- vendor
- node_modules
- docs/example.md
- generated
- package-lock.json
- Rakefile
- VERSIONS
