title: Apache Pulsar
description: Distributed pub-sub messaging system
encoding: utf-8
permalink: pretty
pulsar_repo: https://github.com/apache/incubator-pulsar/tree/master
baseurl: /incubator-pulsar/
destination: ../generated-site

versions:
- 1.18
latest: 1.18

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3

defaults:
- scope:
    path: docs
  values:
    layout: docs
- scope:
    path: ja
  values:
    layout: docs-ja

exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- package.json
- popovers.yaml
- Makefile
- scripts
- vendor
- node_modules
- docs/example.md
- generated
- package-lock.json
- Rakefile
- VERSIONS
