configs:
- name: tickTime
  default: '2000'
  description: The *tick* is the basic unit of time in ZooKeeper, measured in milliseconds and used to regulate things like [heartbeats and timeouts](https://www.tutorialspoint.com/zookeeper/zookeeper_quick_guide.htm). `tickTime` is the length of a single tick.
- name: initLimit
  default: '10'
  description: The maximum time, in ticks, that the leader ZooKeeper server allows follower ZooKeeper servers to successfully connect and sync. The tick time is set in milliseconds using the [`tickTime`](#zookeeper-tickTime) parameter.
- name: syncLimit
  default: '5'
  description: The maximum time, in ticks, that a follower ZooKeeper server is allowed to sync with other ZooKeeper servers. The tick time is set in milliseconds using the [`tickTime`](#zookeeper-tickTime) parameter.
- name: dataDir
  default: data/zookeeper
  description: The location where ZooKeeper will store in-memory database snapshots as well as the transaction log of updates to the database.
- name: clientPort
  default: '2181'
  description: The port on which the ZooKeeper server will listen for connections.
- name: autopurge.snapRetainCount
  default: '3'
  description: In ZooKeeper, auto purge determines how many recent snapshots of the database stored in [`dataDir`](#zookeeper-dataDir) to retain within the time interval specified by [`autopurge.purgeInterval`](#zookeeper-autopurge.purgeInterval) (while deleting the rest).
- name: autopurge.purgeInterval
  default: '1'
  description: The time interval, in hours, by which the ZooKeeper database purge task is triggered. Setting to a non-zero number will enable auto purge; setting to 0 will disable. Read [this guide](http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance) before enabling auto purge.
- name: maxClientCnxns
  default: 60
  description: The maximum number of client connections. Increase this if you need to handle more ZooKeeper clients.
